config/routes.rb
Rails.application.routes.draw do
  resources :payments, except: [:destroy, :edit] do
    member do
      put 'refund'
    end
  end

  root to: redirect(path: :payments)
  # root "payments#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/payment.rb
class Payment < ApplicationRecord

  def refundable?
    return nil if refunded?

    stripe_charge_id.present?
  end

  def refunded?
    refund_id.present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :refund, :update]

  # GET /payments
  # GET /payments.json
  def index
    @payments = Payment.all
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # PUT /payments/refund
  def refund
    if @payment.refundable?
      refund = StripeGateway.new.refund(@payment.stripe_charge_id)
      @payment.refund_id = refund["id"]
      @payment.save
    end

    render :show
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(stripe_token: payment_params[:stripeToken])

    charge = StripeGateway.new.charge(@payment.stripe_token, 
                                  1200, 
                                  {'order_id' => '6735'},
                                  "Whatever I created for...")

    @payment.stripe_charge_id = charge["id"]
    @payment.save

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: 'Payment was successfully created.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
      params.permit(:stripeToken, :stripeTokenType, :stripeEmail)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StripeExercise</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/payments/_form.html.erb
<%= form_with(model: payment, local: true) do |form| %>
  <% if payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% payment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <script
    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= ENV["STRIPE_PUBLISHABLE_KEY"] %>"
    data-email="orbanbotond@gmail.com"
    data-amount="999"
    data-name="Logic Optimum Fee"
    data-description="Example Charge For Test Subscription"
    data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
    data-locale="auto">
  </script>
<% end %>

app/views/payments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Payments</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= link_to 'Show', payment %></td>
        <% if payment.refundable? %>
          <td><%= link_to 'Refund', refund_payment_path(payment), method: :put %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment', new_payment_path %>

app/views/payments/new.html.erb
<h1>New Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Back', payments_path %>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
Refunded: <%= @payment.refunded? %>
<br />
Refundable: <%= @payment.refundable? %>
</p>

<p>
Card Token: <%= @payment.stripe_token %>
<br />
Charge Id: <%= @payment.stripe_charge_id %>
<br />
Stripe Refund Id: <%= @payment.refund_id %>
</p>

<% if @payment.refundable? %>
  <%= link_to 'Refund', refund_payment_path(@payment), method: :put %> |
<% end %>

<%= link_to 'Back', payments_path %>